[[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]] && {
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
}

[[ -f "${0:A:h}/powerlevel10k/powerlevel10k.zsh-theme" ]] && {
    source "${0:A:h}/powerlevel10k/powerlevel10k.zsh-theme"
}

[[ -f "${0:A:h}/p10k.zsh" ]] && source "${0:A:h}/p10k.zsh"
