MINI_ZSH_PLUGIN=${0:A:h}

########### zsh-completions    https://github.com/zsh-users/zsh-completions
[[ -f "$MINI_ZSH_PLUGIN/zsh-completions/zsh-completions.plugin.zsh" ]] && {
    autoload -Uz compinit && compinit
    source "$MINI_ZSH_PLUGIN/zsh-completions/zsh-completions.plugin.zsh"
}

########### zsh-autosuggestions    https://github.com/zsh-users/zsh-autosuggestions
[[ -f "$MINI_ZSH_PLUGIN/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh" ]] && {
    source "$MINI_ZSH_PLUGIN/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"
}

########### zsh-syntax-highlighting    https://github.com/zsh-users/zsh-syntax-highlighting
[[ -f "$MINI_ZSH_PLUGIN/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh" ]] && {
    source "$MINI_ZSH_PLUGIN/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh"
}

########### extract
[[ -f "$MINI_ZSH_PLUGIN/extract.zsh" ]] && {
    source "$MINI_ZSH_PLUGIN/extract.zsh"
}

source "$MINI_ZSH_PLUGIN/fzf.zsh"
