#!/bin/zsh

export LANG="en_US.utf8"
export LC_ALL="en_US.utf8"
export LC_TIME="en_us.utf8"
export LC_CTYPE="en_US.utf8"
########### XDG
export XDG_LOCAL_HOME="$HOME/.local"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"

########### MINI
export MINI="$XDG_CONFIG_HOME/mini"

########### zsh history command
export HISTFILE="$HOME/.zsh_history"
export SAVEHIST=10000

########### tmux tempdir
export TMUX_TMPDIR="/tmp"

########### golang env
export GOPATH="$XDG_LOCAL_HOME/go"
export GOPROXY="https://goproxy.io,direct"

########### rust env
export CARGO_HOME="$XDG_LOCAL_HOME/rust"
export RUSTUP_HOME="$XDG_LOCAL_HOME/rust"
export RUSTUP_DIST_SERVER="https://mirrors.ustc.edu.cn/rust-static"
export RUSTUP_UPDATE_ROOT="https://mirrors.ustc.edu.cn/rust-static/rustup"

########### PATH
function __export() { [[ ${(P)1} != *$2* ]] && export $1=$2:${(P)1} }
__export    "PATH"            "$XDG_LOCAL_HOME/bin"
__export    "PATH"            "$XDG_LOCAL_HOME/go/bin"
__export    "PATH"            "$XDG_LOCAL_HOME/rust/bin"

__export    "CPATH"           "$XDG_LOCAL_HOME/include"
__export    "CPATH"           "$XDG_LOCAL_HOME/mysql/include"
__export    "CPATH"           "$XDG_LOCAL_HOME/hiredis/include"

__export    "LIBRARY_PATH"    "$XDG_LOCAL_HOME/lib"
__export    "LIBRARY_PATH"    "$XDG_LOCAL_HOME/mysql/lib"
__export    "LIBRARY_PATH"    "$XDG_LOCAL_HOME/hiredis/lib"

__export    "LD_LIBRARY_PATH" "$XDG_LOCAL_HOME/lib"
__export    "LD_LIBRARY_PATH" "$XDG_LOCAL_HOME/mysql/lib"
__export    "LD_LIBRARY_PATH" "$XDG_LOCAL_HOME/hiredis/lib"
unfunction __export

###########
setopt NO_NOMATCH
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS

########### ignore <Tab> completion case
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

########### add alias
function __alias() { alias "$1"="$2" }
__alias    "ls"      "ls --color"
__alias    "la"      "ls --color -la"
__alias    "rf"      "rm -rf"
__alias    "lg"      "lazygit"
__alias    "src"     "source $HOME/.zshrc"
__alias    "vrc"     "vim $HOME/.zshrc"
__alias    "vvi"     "vim $MINI/nvim/init.lua"
# tmux
__alias    "tn"      "tmux new -s"
__alias    "ta"      "tmux attach -t"
__alias    "trns"    "tmux rename-session"
__alias    "trnw"    "tmux rename-window"
unfunction __alias

########### add keybinds
bindkey    "\e[1~"    beginning-of-line    # <Home>
bindkey    "^[[H"     beginning-of-line    # <Home>
bindkey    "\e[4~"    end-of-line          # <End>
bindkey    "^[[F"     end-of-line          # <End>
bindkey    "\e[3~"    delete-char          # <Delete>
bindkey    "^[[j~"    delete-char          # <Delete>
bindkey    "\eh"      backward-char        # <Alt-h> <Left>
bindkey    "\ej"      down-line-or-history # <Alt-j> <Down>
bindkey    "\ek"      up-line-or-history   # <Alt-k> <Up>
bindkey    "\el"      forward-char         # <Alt-l> <Right>

########### colorful echo
function cecho() {
    (( $# != 2 )) && echo $1 && return
    case $1 {
        (Red)    echo -e "\e[31m$2\e[0m" ;;
        (Green)  echo -e "\e[32m$2\e[0m" ;;
        (Yellow) echo -e "\e[33m$2\e[0m" ;;
        (Blue)   echo -e "\e[34m$2\e[0m" ;;
        (Cyan)   echo -e "\e[36m$2\e[0m" ;;
        (*)      echo $2 ;;
    }
}

function duh()     { du -h --max-depth=${1:-1} }
function ulimitc() { ulimit -c unlimited }

source "$MINI/zsh/themes/zshrc"
source "$MINI/zsh/plugins/zshrc"
